2025-05-25 05:15:04,316 ERROR: Unhandled Error: (2002, "Can't connect to server on 'localhost' (10061)") [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:53]
2025-05-25 05:15:04,375 ERROR: Traceback (most recent call last):
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\INFO\app.py", line 183, in before_request
    cur = mysql.connection.cursor()
          ^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
                   ^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")
 [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:54]
2025-05-25 05:15:08,502 ERROR: Unhandled Error: (2002, "Can't connect to server on 'localhost' (10061)") [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:53]
2025-05-25 05:15:08,505 ERROR: Traceback (most recent call last):
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\INFO\app.py", line 183, in before_request
    cur = mysql.connection.cursor()
          ^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
                   ^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")
 [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:54]
2025-05-25 05:15:12,621 ERROR: Unhandled Error: (2002, "Can't connect to server on 'localhost' (10061)") [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:53]
2025-05-25 05:15:12,623 ERROR: Traceback (most recent call last):
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\INFO\app.py", line 183, in before_request
    cur = mysql.connection.cursor()
          ^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
                   ^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")
 [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:54]
2025-05-25 05:15:16,708 ERROR: Unhandled Error: (2002, "Can't connect to server on 'localhost' (10061)") [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:53]
2025-05-25 05:15:16,710 ERROR: Traceback (most recent call last):
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\INFO\app.py", line 183, in before_request
    cur = mysql.connection.cursor()
          ^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
                   ^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")
 [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:54]
2025-05-25 05:15:20,802 ERROR: Unhandled Error: (2002, "Can't connect to server on 'localhost' (10061)") [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:53]
2025-05-25 05:15:20,804 ERROR: Traceback (most recent call last):
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\INFO\app.py", line 183, in before_request
    cur = mysql.connection.cursor()
          ^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
                   ^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")
 [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:54]
2025-05-25 05:15:24,894 ERROR: Unhandled Error: (2002, "Can't connect to server on 'localhost' (10061)") [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:53]
2025-05-25 05:15:24,896 ERROR: Traceback (most recent call last):
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\INFO\app.py", line 183, in before_request
    cur = mysql.connection.cursor()
          ^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
                   ^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")
 [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:54]
2025-05-25 05:15:26,302 ERROR: Unhandled Error: (2002, "Can't connect to server on 'localhost' (10061)") [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:53]
