2025-05-25 05:15:26,306 ERROR: Traceback (most recent call last):
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\INFO\app.py", line 183, in before_request
    cur = mysql.connection.cursor()
          ^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
                   ^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")
 [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:54]
2025-05-25 05:15:30,406 ERROR: Unhandled Error: (2002, "Can't connect to server on 'localhost' (10061)") [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:53]
2025-05-25 05:15:30,408 ERROR: Traceback (most recent call last):
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\INFO\app.py", line 183, in before_request
    cur = mysql.connection.cursor()
          ^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
                   ^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")
 [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:54]
2025-05-25 05:15:30,533 ERROR: Unhandled Error: (2002, "Can't connect to server on 'localhost' (10061)") [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:53]
2025-05-25 05:15:30,535 ERROR: Traceback (most recent call last):
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\INFO\app.py", line 183, in before_request
    cur = mysql.connection.cursor()
          ^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
                   ^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")
 [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:54]
2025-05-25 05:15:34,707 ERROR: Unhandled Error: (2002, "Can't connect to server on 'localhost' (10061)") [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:53]
2025-05-25 05:15:34,709 ERROR: Traceback (most recent call last):
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\INFO\app.py", line 183, in before_request
    cur = mysql.connection.cursor()
          ^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
                   ^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")
 [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:54]
2025-05-25 05:15:38,720 ERROR: Unhandled Error: (2002, "Can't connect to server on 'localhost' (10061)") [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:53]
2025-05-25 05:15:38,722 ERROR: Traceback (most recent call last):
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\INFO\app.py", line 183, in before_request
    cur = mysql.connection.cursor()
          ^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
                   ^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")
 [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:54]
2025-05-25 05:15:38,783 ERROR: Unhandled Error: (2002, "Can't connect to server on 'localhost' (10061)") [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:53]
2025-05-25 05:15:38,786 ERROR: Traceback (most recent call last):
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\INFO\app.py", line 183, in before_request
    cur = mysql.connection.cursor()
          ^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
                   ^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")
 [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:54]
2025-05-25 05:15:50,787 ERROR: Unhandled Error: (2002, "Can't connect to server on 'localhost' (10061)") [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:53]
